### ISSUE TITLE
Add or replace Manga Origines with PhenixScans to the french manga sources

### ISSUE THREAD

**Issue by lvllaby** [KotatsuApp/kotatsu-parsers#173]
### Describe your suggested feature

Add or replace Manga Origines with 
[PhenixScans](https://phenixscans.fr) to the french manga sources, this is the ancient trad team of the Manga Origines but they separated after the hack of the site of the Manga Origines

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Unfortunately I have no access to phenixscans.fr (due to the CloudFlare). Can you please explain a bit more about "Manga Origines" (what it is?). 
If you change domain of CosmicScans source to phenixscans.fr, is it works?

**Comment by drsgdfnhtyjktyjt** [comment]
Manga-origine was a manga website that closed after a hack and the founders of manga-origine created PhenixScans.


I think he's talking about CosmicScans because it uses the same template, I've put up a screen.

I don't have the skills to add it yet, but if anyone knows how to add a mangareader template, help is welcome.

![p](https://github.com/KotatsuApp/kotatsu-parsers/assets/70220050/bbc64aa7-88bb-444b-b3c1-893c82fe902d)

![image](https://github.com/KotatsuApp/kotatsu-parsers/assets/70220050/32a4827d-3e87-47ca-9585-d7facd2cb544)

**Comment by drsgdfnhtyjktyjt** [comment]
I propose this code, but since I can't test it, I'd like to ask if someone can test it before creating a pr

```@MangaSourceParser("PHENIXSCANS", "Phenixscans", "fr")
	class PhenixscansParser(context: MangaLoaderContext) :
		MangaReaderParser(context, MangaSource.PHENIXSCANS, pageSize = 20, searchPageSize = 10) {
		override val configKeyDomain: ConfigKey.Domain
			get() = ConfigKey.Domain("phenixscans.fr")

		override val listUrl: String
			get() = "/manga"
		override val tableMode: Boolean
			get() = false

		override val chapterDateFormat: SimpleDateFormat = SimpleDateFormat("MMM d, yyyy", Locale.ENGLISH)

		override suspend fun parseInfoList(docs: Document, manga: Manga, chapters: List<MangaChapter>): Manga {
			val infoElement = docs.selectFirst("div.infox")
			return manga.copy(
				chapters = chapters,
				description = infoElement?.selectFirst("div.entry-content")?.html(),
				author = infoElement?.selectFirst(".flex-wrap div:contains(Auteur)")?.lastElementSibling()?.text(),
				tags = infoElement?.select(".wd-full .mgen > a")
					?.mapNotNullToSet { getOrCreateTagMap()[it.text()] }
					.orEmpty(),
			)
		}
	}

**Comment by davvarrr** [comment]
source added need to close issues
