### ISSUE TITLE
Shinigami error

### ISSUE THREAD

**Issue by diecko69** [KotatsuApp/kotatsu-parsers#319]
### Source information

shinigami

### Steps to reproduce

1.
![Screenshot_20231020-000315_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/140547712/0c41c6a9-92d4-4961-a2d7-918edc5dfc60)

### Kotatsu version

6.2.2

### Android version

Android 13

### Other details

cannot be opened in Kotatsu but can be opened in browser, please fix the issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
doujindesu fixed with this commit : [#87032a6](https://github.com/KotatsuApp/kotatsu-parsers/commit/87032a6835787d37dea37ca5a520a2a278aceab3), but for shinigami you'll have to check with the devs because there's an obligatory captcha as soon as you arrive on the site and the app doesn't detect it to resolve it manually.

**Comment by davvarrr** [comment]
Shinigami works now
