### ISSUE TITLE
some changed manga sources and and merges

### ISSUE THREAD

**Issue by Baturax** [KotatsuApp/kotatsu-parsers#321]
### Source information

mangakeyfi.net and webtoontr.net merged. mangakeyfi.net can be removed.  monomanga.com became manga-tr.com  can't read on viyafansub because it wants to log in  yaoitr.com became yaoitr.online  no mangas appear in afroditscans  error in mangaokutr.com

### Kotatsu version

latest

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
For sources to remove or change the url, I'll do it.
For afroditscans.com the error is already known : -> #198 
For mangaokutr.com you'll have to ask the dev to look into it I've put more info in Known problems
For viyafansub ideally you should go to a non 18+ manga page and log in by opening the manga page ( in theory it should work because -18 works fine )
