### ISSUE TITLE
Nhentai.net: Multiple same results 

### ISSUE THREAD

**Issue by kyoyacchi** [KotatsuApp/kotatsu-parsers#402]
### Source information

Nhentai.net

### Steps to reproduce

Search an doujinshi on nhentai.
Scroll down.
it shows same results as i scroll down

### Kotatsu version

6.4.2

### Android version

Android 11

### Other details

https://github.com/KotatsuApp/kotatsu-parsers/assets/63583961/44badf89-8d74-4ec8-9fe3-c469cee3c7f9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
I added a fix in this pr : #401 
For more info on what's happening, you enter a manga id, so the source doesn't return a list of manga, but sends you directly to the manga, so the app sends you the manga it's found, i.e. the manga recommended at the bottom of the page, and since there's no pagination, the page turns in a loop.
