### ISSUE TITLE
Demon Sect does not show the pages of the works.

### ISSUE THREAD

**Issue by EvaldoCeBr** [KotatsuApp/kotatsu-parsers#820]
### Source information

DemonSect

### Steps to reproduce

Whenever I try to load the pages of the works, I get an error.
![Screenshot_2024-05-29-15-45-51-017_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/169321265/7cb7a498-f8ed-4744-a2ac-e4a4ada7eaf3)

### Kotatsu version

7.1.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by DollynDeveloper** [comment]
In English:

This problem is probably due to the fact that, in order to access the works in the site's catalog, one must log in to it. Try to view the page in the webview and log in, if it works, remember to close the issue here on Github. 

Em português:

Este problema provavelmente se deve ao fato de que, para acessar as obras no catálogo do site, deve-se realizar login no mesmo. Tente visualizar a página na webview e realizar o login, caso funcione, lembre-se de fechar o issue aqui no Github.
